"""Run a stored LeetCode solution against the problem's own example inputs.

Auto-generated by leetvault - do not edit; it is rewritten on sync.

Usage:
    python leetvault_runner.py Problems/two-sum
    python Problems/two-sum/run.py          # equivalent, from anywhere

Prints your solution's output for each example. It does *not* assert correctness:
LeetCode's API exposes example *inputs* but not their expected outputs (those exist only
in the prose of the problem statement), so any pass/fail verdict here would be guesswork.
Compare against the "Output:" lines in that problem's question.md.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any

# LeetCode's judge preloads these into every submission's namespace, so stored solutions
# routinely use `List[int]` etc. with no import. Executing such a file as-is raises
# NameError, so the same names have to be provided here.
from collections import Counter, defaultdict, deque  # noqa: F401
from typing import Deque, Dict, List, Optional, Set, Tuple  # noqa: F401,UP035
import bisect  # noqa: F401
import heapq  # noqa: F401
import itertools  # noqa: F401
import math  # noqa: F401
import re  # noqa: F401
import string  # noqa: F401


class ListNode:
    """LeetCode's singly-linked list node."""

    def __init__(self, val: int = 0, next: "ListNode | None" = None) -> None:
        self.val = val
        self.next = next


class TreeNode:
    """LeetCode's binary tree node."""

    def __init__(
        self, val: int = 0, left: "TreeNode | None" = None, right: "TreeNode | None" = None
    ) -> None:
        self.val = val
        self.left = left
        self.right = right


_PRELOADED: dict[str, Any] = {
    "List": List,
    "Dict": Dict,
    "Set": Set,
    "Tuple": Tuple,
    "Optional": Optional,
    "Deque": Deque,
    "deque": deque,
    "defaultdict": defaultdict,
    "Counter": Counter,
    "heapq": heapq,
    "bisect": bisect,
    "math": math,
    "itertools": itertools,
    "re": re,
    "string": string,
    "ListNode": ListNode,
    "TreeNode": TreeNode,
}

# Param types that are plain JSON and so can be passed straight through.
_SIMPLE_TYPES = {
    "integer",
    "long",
    "double",
    "float",
    "string",
    "boolean",
    "character",
    "integer[]",
    "integer[][]",
    "string[]",
    "string[][]",
    "double[]",
    "boolean[]",
    "list<integer>",
    "list<string>",
    "list<list<integer>>",
    "list<list<string>>",
}


def _load_solution(problem_dir: Path) -> Any:
    """exec the stored solution with LeetCode's implicit names available."""
    candidates = sorted(problem_dir.glob("latest.*"))
    if not candidates:
        raise SystemExit(f"no latest.* solution file in {problem_dir}")
    source_path = candidates[0]
    if source_path.suffix != ".py":
        raise SystemExit(
            f"{source_path.name} is not Python; this runner only executes Python solutions."
        )

    namespace: dict[str, Any] = dict(_PRELOADED)
    namespace["__name__"] = "leetvault_solution"
    exec(compile(source_path.read_text(encoding="utf-8"), str(source_path), "exec"), namespace)

    solution_cls = namespace.get("Solution")
    if solution_cls is None:
        raise SystemExit(f"{source_path.name} defines no `Solution` class.")
    return solution_cls()


def _parse_cases(raw: str, param_count: int) -> list[list[Any]]:
    lines = [ln for ln in raw.splitlines() if ln.strip() != ""]
    if param_count <= 0 or len(lines) % param_count != 0:
        return []
    cases: list[list[Any]] = []
    for i in range(0, len(lines), param_count):
        chunk = lines[i : i + param_count]
        try:
            cases.append([json.loads(v) for v in chunk])
        except json.JSONDecodeError:
            return []
    return cases


def run(problem_dir: Path) -> int:
    metadata_path = problem_dir / "metadata.json"
    if not metadata_path.exists():
        raise SystemExit(f"no metadata.json in {problem_dir}")
    metadata = json.loads(metadata_path.read_text(encoding="utf-8"))

    runner_info = metadata.get("runner") or {}
    method_name = runner_info.get("method")
    params = runner_info.get("param_types") or []
    raw_cases = runner_info.get("example_testcases") or ""

    print(f"{metadata.get('frontend_id')}. {metadata.get('title')}  [{metadata.get('difficulty')}]")
    print("-" * 60)

    if not method_name:
        print("This problem has no single entry point (a design/interactive problem),")
        print("so it can't be driven automatically. Run it manually instead.")
        return 0

    unsupported = [t for t in params if t not in _SIMPLE_TYPES]
    if unsupported:
        print(f"Parameter type(s) {unsupported} need custom construction")
        print("(e.g. linked lists or trees), so inputs can't be built automatically.")
        print(f"Call Solution().{method_name}(...) yourself with the inputs you want.")
        return 0

    cases = _parse_cases(raw_cases, len(params))
    if not cases:
        print("No usable example inputs were stored for this problem.")
        return 0

    solution = _load_solution(problem_dir)
    method = getattr(solution, method_name, None)
    if method is None:
        print(f"Your solution has no method named `{method_name}`.")
        return 1

    for i, args in enumerate(cases, start=1):
        rendered = ", ".join(json.dumps(a) for a in args)
        try:
            result = method(*args)
        except Exception as exc:  # noqa: BLE001 - report, don't crash the whole run
            print(f"Example {i}: {rendered}")
            print(f"  raised {type(exc).__name__}: {exc}\n")
            continue
        print(f"Example {i}: {rendered}")
        print(f"  -> {result!r}\n")

    print("Expected outputs are in question.md (LeetCode's API doesn't expose them).")
    return 0


def main(argv: list[str]) -> int:
    if len(argv) < 2:
        print(__doc__)
        return 1
    return run(Path(argv[1]).resolve())


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
