"""Run this problem's stored solution against LeetCode's example inputs.

Auto-generated by leetvault - do not edit; it is rewritten on sync.
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

from leetvault_runner import run  # noqa: E402

if __name__ == "__main__":
    raise SystemExit(run(Path(__file__).resolve().parent))
